<?php $this->layout('layout::default') ?>

<h2 class="text-center title text-family">
    Comment me contacter pour plus de renseignements :
</h2>
<div class="embed-responsive embed-responsive-1by1 h-25">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d18019.196280110362!2d6.318258068143074!3d48.810718058080624!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x479493b653e130c1%3A0xb7d30b2a31906337!2s1%20Place%20des%20Hortensias%2C%2054760%20Lanfroicourt!5e0!3m2!1sfr!2sfr!4v1600591683883!5m2!1sfr!2sfr" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
</div>
<div class="text-center w-100 mb-2 text-family price">
    (3 place des Hotensias 54760 Lanfroicourt)
</div>
<div class="row text-family">
	<div class="col-12 text-center">
		<div class="description">
            Rendez-vous du lundi au vendredi de 07h à 17h au cabinet.<br />
            Le premier et le troisième lundi de chaque mois, la matinée consultation à la maison médicale de Morhange.
        </div>
	</div>
    <div class="col-6 text-right price">
        Par téléphone : <br />
        Par mail : <br />
        Via Facebook : <br />
    </div>
    <div class="col-6 text-left price">
        <span>06.36.90.92.18</span><br />
        <a href="mailto:generic57@hotmail.com">Contact</a><br />
        <a href="https://www.facebook.com/generic57" target="_blank">
            Messenger
        </a><br />
    </div>
</div>
