<?php $this->layout('layout::default') ?>

<div class="text-center error-logo mt-4 text-danger">
    <span class="fa-stack">
        <i class="fas fa-search fa-stack-1x fa-rotate-90"></i>
        <i class="fas fa-ban fa-stack-2x"></i>
    </span>
</div>
<h1 class="text-center error-title mt-2">Désolé</h1>
<h3 class="text-center error-subtitle">Impossible de trouver la page demandée.</h3>
<p class="text-center error-description">
    Si le problème persiste veuillez contacter les administrateurs du site.
</p>
