<?php $this->layout('layout::default') ?>

<div class="text-center error-logo mt-4 text-danger">
    <i class="fas fa-exclamation-triangle"></i>
</div>
<h1 class="text-center error-title mt-2">Désolé</h1>
<h3 class="text-center error-subtitle">Une erreur est survenue, essayez à nouveau.</h3>
<p class="text-center error-description">
    Si le problème persiste veuillez contacter les administrateurs du site.
</p>