<nav class="navbar navbar-expand-lg navbar-dark bg-success">
    <a class="navbar-brand" href="<?= $this->url('home') ?>"><img src="<?= $this->basePath('img/logos/logo.png') ?>" height="37" class="mr-3" alt="logo">Gen'eric</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <?= $this->renderMenu() ?>
        </ul>
    </div>
</nav>