<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $this->e($title) ?></title>
    <link rel="shortcut icon" href="<?= $this->basePath('favicon.ico') ?>" />
    <?= $this->insert('partials::styles', ['styles' => $this->section('stylesheets')])?>
</head>
<body>
<?php if ($this->section('menu')):?>
    <?= $this->section('menu')?>
<?php else :?>
    <?= $this->insert('partials::menu') ?>
<?php endif;?>
<div class="container-fluid contenu-app">

    <div class="row">
        <div class="col-12 contenu-page">
            <?= $this->section('content')?>
        </div>
    </div>

    <div class="row">
        <div class="col-12 text-center">
            <footer class="app-footer">
                <hr />
                <?php if ($this->section('footer')): ?>
                    <?=$this->section('footer')?>
                <?php else: ?>
                    <div class="mt-2 contact-icon">
                        <a href="https://www.facebook.com/generic57" target="_blank">
                            <i class="fab fa-facebook fa-2x"></i>
                        </a>
                    </div>
                    <p>
                        &copy; <?=date('Y')?> Shishi. Tous droits réservés.
                    </p>
                <?php endif ?>
            </footer>
        </div>
    </div>
</div>

<?= $this->insert('partials::scripts', ['scripts' => $this->section('javascript')])?>
</body>
</html>
