<?php $this->layout('layout::default') ?>
<div class="row justify-content-md-center mt-lg-4 mt-2">
    <div class="col col-lg-6 text-center description text-family">
        <p>
            Bonjour, je m'appelle Eric. Je suis âgé de 40 ans et je suis en pleine reconversion professionnelle. Après avoir passé de nombreuses années dans le monde de l'industrie, je saute enfin
            le pas et j'ai trouvé ma voix celle que j'avais vraiment envie de faire.
        </p>
        <p>
            Aujourd'hui, je lance ma micro-entreprise dans le domaine du bien-être, je me suis formé au Reiki (soins énergétiques). Oui quelques personnes encore en <?=date('Y')?>
            sont sceptiques  et sourient quand je leur parle de soins énergétiques, mais je peux le dire haut et fort : "ça fonctionne pour plein de choses".
        </p>
        <p>
            Je me suis également formé en Aromathérapie (huiles essentielles bio) avec lesquelles je suis devenu très ami, d'une synergie (potion) entrainant une autre.
            Une fois pris dedans, il est très difficile d'en sortir mais toutefois, il faut faire très attention car les huiles peuvent être nos amies mais elles peuvent être très dangereuses
            voila pourquoi il faut être très vigilant.
        </p>
    </div>
</div>