<?php $this->layout('layout::default') ?>

<div class="text-center mb-3 text-family title">
    Praticien Reiki, Aromathérapie et Massothérapeute
</div>

<div class="text-center mt-3">
    <img src="<?= $this->basePath('/img/logos/logo.png') ?>" alt="logo" class="img-fluid d-none d-lg-inline" />
</div>

<div class="row justify-content-md-center">
    <div class="col col-lg-6 text-center mt-2 mt-lg-5 chapter-header text-family">
        <u class="font-weight-bolder">Qu'est-ce que le soin Reiki et quels sont ses bienfait ?</u>
    </div>
</div>
<div class="row justify-content-md-center mt-lg-4 mt-2">
    <div class="col col-lg-6 text-center text-family description">
        <p>
            Le Reiki est une forme de thérapie alternative communément appelée guérison énergétique.
        </p>
        <p>
            Elle est apparue au Japon à la fin des années 1800 et on dit d'elle qu'elle  implique le transfert d'énergie universelle des paumes de la main du praticien à son patient, elle s'appuie sur le champ vibratoire de ce dernier.
        </p>
        <p>
            La guérison par l'énergie a été utilisée pendant des siècles sous diverses formes. Les partisans disent qu'elle fonctionne gràce aux champs d'énergie autour du corps.<br />
            Une certaine controverse entoure le Reiki, car il est difficile de prouver son efficacité par des moyens scientifiques. Cependant beaucoup de gens qui pratiquent le Reiki disent qu'il fonctionne, et sa popularité augmente, tant et si bien que le Reiki est même pratiqué en complément dans certains hôpitaux.
        </p>
    </div>
</div>

<div class="row justify-content-md-center mt-lg-2">
    <div class="col col-lg-6 text-center chapter-header text-family">
        <u>Les massages synergiques</u>
    </div>
</div>

<div class="row justify-content-md-center mt-lg-4 mt-2">
    <div class="col col-lg-6 text-center description text-family">
        <p>
            La synergie thérapeutique est une association de plusieurs techniques de massages. Elle vise à une meilleure prise en charge de chaque problématique, dans le but d'en optimiser les résultats lors de la séances.
        </p>
        <u class="font-weight-bold list-header">Les principales indications :</u>
        <ul class="list-unstyled">
            <li>
                Tensions musculaires et articulaires.
            </li>
            <li>
                Tensions nerveuses, stress, fatigue.
            </li>
            <li>
                Troubles du sommeil.
            </li>
            <li>
                Céphalées, migraines.
            </li>
            <li>
                Troubles digestifs.
            </li>
            <li>
                Elimination des toxines.
            </li>
            <li>
                Problèmes circulatoires, rétention d'eau, cellulite.
            </li>
        </ul>
        <p>
            La synergie thérapeutique proposée durant une séance regroupe les techniques du massage traditionnel chinois (Tui Na), de la Réflexologie et du Drainage Lymphatique Energique.
        </p>
    </div>
</div>